---
- name: Get Join command from controller
  hosts: kube_master
  gather_facts: false
  become: true
  tasks:
    - name: Get join command
      ansible.builtin.command: 
        cmd: kubeadm token create --print-join-command
      register: join_command

    - name: Set join command
      ansible.builtin.set_fact:
        join_command_line: "{{ join_command.stdout_lines[0] }}"
      delegate_facts: true
      delegate_to: "{{ item }}"
      loop: "{{groups['kube_worker']}}"


- name: Join Cluster
  hosts: kube_worker
  become: true
  tasks:
    - name: Run command to join Cluster
      ansible.builtin.shell:
        cmd: "{{ join_command_line }}"