---
- name: Check if api server manifest already exist
  become: true
  ansible.builtin.stat:
    path: '/etc/kubernetes/manifests/kube-apiserver.yaml'
  register: api_server_check

- name: Initialize the cluster control plane
  ansible.builtin.command:
    cmd: kubeadm init --control-plane-endpoint={{ ansible_facts['eth0']["ipv4"]['address'] }} --node-name {{ ansible_facts['hostname'] }} --pod-network-cidr=10.244.0.0/16
  when: not api_server_check.stat.exists

- name: Create .kube directory
  become: true
  become_user: "{{ kube_admin_user }}"
  ansible.builtin.file:
    path: $HOME/.kube
    state: directory
    mode: '0755'

- name: Copy admin.conf to user kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ kube_admin_user }}/.kube/config"
    owner: "{{ kube_admin_user }}"
    mode: '0644'
    remote_src: true

- name: Install CNI Flannel plugin - POD network
  become: true
  become_user: "{{ kube_admin_user }}"
  ansible.builtin.command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  args:
    chdir: $HOME
    creates: flannel_pod_network_setup.log
  when: ansible_facts['flannel.1'] is not defined
